// Regenerate the icon subset. Run after adding a new icon:  npm run icons:build
// Requires pyftsubset (pip install fonttools brotli). Generated files are committed, so a normal
// build/deploy needs none of this.
//
// TWO FACES. Tabler ships outline icons and *-filled icons as separate fonts, each with its own CSS
// that claims the .ti class. The app was only ever importing the outline sheet, so every filled icon it
// used (ti-circle-check-filled, ti-star-filled, …) had no glyph and rendered blank. We subset both and
// give the filled classes their own family, so both kinds work from one stylesheet.
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fontIcons, usedIcons } from './icons-scan.mjs';

const DIST = 'node_modules/@tabler/icons-webfont/dist';
const FACES = [
  { key: 'outline', family: 'tabler-icons', css: `${DIST}/tabler-icons.min.css`, font: `${DIST}/fonts/tabler-icons.woff2`, out: 'src/assets/tabler-subset.woff2' },
  { key: 'filled', family: 'tabler-icons-filled', css: `${DIST}/tabler-icons-filled.min.css`, font: `${DIST}/fonts/tabler-icons-filled.woff2`, out: 'src/assets/tabler-filled-subset.woff2' },
];

fs.mkdirSync('src/assets', { recursive: true });
const blocks = [];
let total = 0, bytes = 0;

// The two sheets use the SAME class names against DIFFERENT fonts — they're alternatives, not additions.
// So `ti-circle-check-filled`, which this app uses in several places, is not a real Tabler class in any
// sheet; it's the name from their React package. Those icons have always rendered blank. We keep the app's
// names working by mapping any `x-filled` to glyph `x` in the FILLED face and scoping the family per class.
const outlineKnown = fontIcons(FACES[0].css);
const filledKnown = fontIcons(FACES[1].css);
const allUsed = usedIcons('src', new Map([...outlineKnown, ...[...filledKnown].map(([n, c]) => [n + '-filled', c])]));
const pick = {
  outline: allUsed.filter((n) => !n.endsWith('-filled')),
  filled: allUsed.filter((n) => n.endsWith('-filled')),
};
for (const face of FACES) {
  const known = face.key === 'filled'
    ? new Map(pick.filled.map((n) => [n, filledKnown.get(n.replace(/-filled$/, ''))]).filter(([, c]) => c))
    : outlineKnown;
  const used = face.key === 'filled' ? [...known.keys()].sort() : pick.outline;
  if (!used.length) continue;
  fs.writeFileSync(`/tmp/fdc-uni-${face.key}.txt`, used.map((n) => 'U+' + known.get(n).toUpperCase()).join(','));
  execFileSync('pyftsubset', [
    face.font, `--unicodes-file=/tmp/fdc-uni-${face.key}.txt`, '--flavor=woff2',
    '--layout-features=', '--no-hinting', '--desubroutinize', `--output-file=${face.out}`,
  ], { stdio: 'inherit' });
  const size = fs.statSync(face.out).size;
  total += used.length; bytes += size;
  blocks.push({ face, used, known, size });
  console.log(`  ${face.key}: ${used.length} icons, ${(size / 1024).toFixed(1)} KB`);
}

const fontFaces = blocks.map(({ face }) => `@font-face{
  font-family:"${face.family}";
  font-style:normal;font-weight:400;font-display:block;
  src:url("./assets/${face.out.split('/').pop()}") format("woff2");
}`).join('\n');

const rules = blocks.map(({ face, used, known }) => used.map((n) =>
  face.key === 'filled'
    ? `.ti-${n}:before{content:"\\${known.get(n)}"}\n.ti-${n}{font-family:"${face.family}"!important}`
    : `.ti-${n}:before{content:"\\${known.get(n)}"}`).join('\n')).join('\n');

fs.writeFileSync('src/icons.css', `/* Tabler icons — SUBSET, generated by tools/icons-build.mjs. Do not hand-edit.
   The full webfont ships thousands of glyphs across .ttf (2.7 MB), .woff (776 KB) and .woff2 (452 KB);
   this app draws ${total}. Subsetting to those and serving woff2 only takes the icon payload from
   ~4.4 MB to ~${Math.round(bytes / 1024)} KB. Every browser this app supports has read woff2 since 2016.
   Both the outline and the *-filled face are included — the filled one was never imported before, so
   every filled icon in the app was silently rendering as a blank square. */
${fontFaces}
.ti{
  font-family:"tabler-icons"!important;
  speak:none;font-style:normal;font-weight:400;font-variant:normal;text-transform:none;
  line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;
  display:inline-block;
}
${rules}
`);
console.log(`icon subset rebuilt: ${total} icons, ${(bytes / 1024).toFixed(1)} KB total`);
